export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS";
export const PRODUCTS_FETCH_FAILURE = "PRODUCTS_FETCH_FAILURE";
export const PRODUCTS_FETCH_IS_LOADING = "PRODUCTS_FETCH_IS_LOADING";


export const ORDERS_FETCH_SUCCESS = "ORDERS_FETCH_SUCCESS";


export const CART_PRODUCTS_FETCH_SUCCESS = "CART_PRODUCTS_FETCH_SUCCESS";
export const CART_PRODUCTS_FETCH_FAILURE = "CART_PRODUCTS_FETCH_FAILURE";
export const CART_PRODUCTS_FETCH_IS_LOADING = "PRODUCTS_FETCH_IS_LOADING";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
